ALTER TABLE "notifications" DROP CONSTRAINT "notifications_type_check";
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_type_check"
CHECK ("notification_type" IN (
  'AUTHORIZATION_READY_TO_DISPENSE',
  'DISPENSATION_LOCATION_ASSIGNED',
  'DISPENSATION_LOCATION_CHANGED',
  'EPS_DIRECTION_PENDING',
  'EPS_TARIFF_ANNEX_REJECTED',
  'AUTHORIZATION_IMPORT_REJECTED',
  'DISPENSATION_DATE_REPORTED',
  'APPLICATION_DATE_REPORTED',
  'DAILY_OPERATIONAL_REPORT'
));
