-- ESP-007: Medicarte operational receipt. No inventory is created here.
ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_status_check";
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_status_check" CHECK ("status" IN ('DRAFT','ISSUED','UNDER_OLP_REVIEW','ACCEPTED','PARTIALLY_ACCEPTED','REJECTED','CANCELLED','IN_FULFILLMENT','PARTIALLY_DISPATCHED','FULLY_DISPATCHED','PARTIALLY_RECEIVED','RECEIVED'));
ALTER TABLE "deliveries" DROP CONSTRAINT "deliveries_status_check";
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_status_check" CHECK ("status" IN ('DRAFT','DISPATCHED','RECEIVED','CANCELLED'));
CREATE TABLE "receipts" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "delivery_id" uuid NOT NULL REFERENCES "deliveries"("id") ON DELETE RESTRICT, "status" varchar(20) DEFAULT 'DRAFT' NOT NULL, "conformity" varchar(30), "received_at" timestamptz DEFAULT now() NOT NULL, "confirmed_at" timestamptz, "created_by" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT, "updated_by" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT, "version" integer DEFAULT 1 NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "receipts_status_check" CHECK ("status" IN ('DRAFT','CONFIRMED')), CONSTRAINT "receipts_conformity_check" CHECK ("conformity" IS NULL OR "conformity" IN ('CONFORMING','PARTIALLY_CONFORMING','NON_CONFORMING')));
CREATE UNIQUE INDEX "receipts_delivery_idx" ON "receipts" ("delivery_id");
CREATE TABLE "receipt_lines" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "receipt_id" uuid NOT NULL REFERENCES "receipts"("id") ON DELETE RESTRICT, "delivery_line_id" uuid NOT NULL REFERENCES "delivery_lines"("id") ON DELETE RESTRICT, "dispatched_quantity" integer NOT NULL, "received_quantity" integer NOT NULL, "accepted_quantity" integer NOT NULL, "rejected_quantity" integer NOT NULL, "shortage_quantity" integer NOT NULL, "expected_lot_number" varchar(255) NOT NULL, "expected_expiration_date" date NOT NULL, "received_lot_number" varchar(255), "received_expiration_date" date, "conformity" varchar(30), "nonconformity_reason" varchar(40), "observation" text, CONSTRAINT "receipt_lines_quantities_check" CHECK ("dispatched_quantity" >= 0 AND "received_quantity" >= 0 AND "accepted_quantity" >= 0 AND "rejected_quantity" >= 0 AND "shortage_quantity" >= 0 AND "received_quantity" <= "dispatched_quantity" AND "accepted_quantity" + "rejected_quantity" = "received_quantity" AND "shortage_quantity" = "dispatched_quantity" - "received_quantity"));
CREATE UNIQUE INDEX "receipt_lines_receipt_delivery_line_idx" ON "receipt_lines" ("receipt_id", "delivery_line_id");
INSERT INTO "permissions" ("id","code","description") VALUES (gen_random_uuid(),'medicarte_receipts.read','Read Medicarte receipts'),(gen_random_uuid(),'medicarte_receipts.manage','Create and confirm Medicarte receipts') ON CONFLICT ("code") DO NOTHING;
INSERT INTO "role_permissions" ("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code" IN ('MTD_ADMIN','MTD_OPERATOR','MTD_GENERAL','MTD_AUDITORIA','READ_ONLY','OLP_OPERATOR','MEDICARTE_OPERATOR') AND p."code"='medicarte_receipts.read' ON CONFLICT DO NOTHING;
INSERT INTO "role_permissions" ("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code"='MEDICARTE_OPERATOR' AND p."code"='medicarte_receipts.manage' ON CONFLICT DO NOTHING;
