/**
 * ESP-017 rule registry. Shared by the engine, API, ADR and catalog.
 * Reconciliation verifies operational invariants. It is not a source of truth
 * and never repairs data.
 */

export const RECONCILIATION_RULES_VERSION = 'ESP-017.1' as const;

export const RECONCILIATION_MAX_FINDINGS_PER_RULE = 1000;
export const RECONCILIATION_STATEMENT_TIMEOUT_MS = 30_000;

export const RECONCILIATION_RUN_STATUSES = ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED'] as const;
export type ReconciliationRunStatus = (typeof RECONCILIATION_RUN_STATUSES)[number];

export const RECONCILIATION_RULE_STATUSES = [
  'PASS',
  'FAIL',
  'NOT_APPLICABLE',
  'ERROR_EXECUTING_RULE',
] as const;
export type ReconciliationRuleStatus = (typeof RECONCILIATION_RULE_STATUSES)[number];

export const RECONCILIATION_CATEGORIES = [
  'INTEGRITY',
  'CONSISTENCY',
  'RECONCILIATION',
  'OBSERVATION',
] as const;
export type ReconciliationCategory = (typeof RECONCILIATION_CATEGORIES)[number];

export const RECONCILIATION_SEVERITIES = ['CRITICAL', 'ERROR', 'WARNING', 'INFO'] as const;
export type ReconciliationSeverity = (typeof RECONCILIATION_SEVERITIES)[number];

export const RECONCILIATION_DOMAINS = [
  'SCHEDULING',
  'DEMAND',
  'PURCHASE',
  'DELIVERY',
  'RECEIPT',
  'INVENTORY',
  'TRANSFER',
  'APPLICATION',
  'OUTCOME',
  'AUDIT',
  'ANALYTICS',
  'BULK',
  'SCOPE',
  'LEGACY',
] as const;
export type ReconciliationDomain = (typeof RECONCILIATION_DOMAINS)[number];

export const RECONCILIATION_DETECTION_MODES = [
  'PREVENTED_BY_DB',
  'DETECTABLE_BY_RECONCILIATION',
  'BOTH',
  'RUNTIME_CONTRACT',
  'OWNED_BY_OTHER',
  'NOT_IMPLEMENTED_NO_EVIDENCE',
] as const;
export type ReconciliationDetectionMode = (typeof RECONCILIATION_DETECTION_MODES)[number];

export type ReconciliationRuleDefinition = Readonly<{
  ruleCode: string;
  version: string;
  domain: ReconciliationDomain;
  category: ReconciliationCategory;
  defaultSeverity: ReconciliationSeverity;
  description: string;
  applicability: string;
  sourceTables: readonly string[];
  expectedInvariant: string;
  findingEvidence: string;
  recommendedAction: string;
  detectionMode: ReconciliationDetectionMode;
  ownedBy?: string;
  executable: boolean;
}>;

function define(definition: ReconciliationRuleDefinition): ReconciliationRuleDefinition {
  return definition;
}

const V = RECONCILIATION_RULES_VERSION;

export const RECONCILIATION_RULES: readonly ReconciliationRuleDefinition[] = [
  define({
    ruleCode: 'REC-SCH-001',
    version: V,
    domain: 'SCHEDULING',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Más de una programación activa con la misma identidad vigente (authorization_item, punto, fecha).',
    applicability: 'patient_schedules en SCHEDULED/RESCHEDULED',
    sourceTables: ['patient_schedules'],
    expectedInvariant:
      'Identidad activa única por (authorization_item_id, dispensing_point_id, scheduled_date)',
    findingEvidence: '{authorizationItemId, dispensingPointId, scheduledDate, activeCount}',
    recommendedAction:
      'Investigar filas activas duplicadas. No cancelar ni fusionar programaciones sin análisis del historial.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCH-002',
    version: V,
    domain: 'SCHEDULING',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'La revisión actual de la programación no coincide con el máximo reconstruible desde patient_schedule_history.',
    applicability: 'patient_schedules con al menos una fila de history',
    sourceTables: ['patient_schedules', 'patient_schedule_history'],
    expectedInvariant:
      'revision actual = max(history.revision) y el snapshot coincide con esa revisión',
    findingEvidence: '{patientScheduleId, currentRevision, historyMaxRevision}',
    recommendedAction:
      'Comparar patient_schedules con patient_schedule_history. No reescribir history.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCH-003',
    version: V,
    domain: 'SCHEDULING',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Programación NEXT_PERIOD sin deferred_planning_period_id.',
    applicability: 'late_handling = NEXT_PERIOD',
    sourceTables: ['patient_schedules'],
    expectedInvariant: 'NEXT_PERIOD exige deferred_planning_period_id',
    findingEvidence: '{patientScheduleId, lateHandling}',
    recommendedAction:
      'Revisar el CHECK de coherencia y el origen de la fila. No inventar un período diferido.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCH-004',
    version: V,
    domain: 'SCHEDULING',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description:
      'Período diferido inexistente o no posterior al período original cuando NEXT_PERIOD lo exige.',
    applicability: 'late_handling = NEXT_PERIOD con deferred_planning_period_id',
    sourceTables: ['patient_schedules', 'planning_periods'],
    expectedInvariant:
      'deferred.start_date > original.end_date (no exige ser el inmediatamente siguiente)',
    findingEvidence: '{patientScheduleId, planningPeriodId, deferredPlanningPeriodId}',
    recommendedAction:
      'Verificar fechas de períodos. No exigir adyacencia estricta: un período posterior no contiguo es válido.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEM-001',
    version: V,
    domain: 'DEMAND',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'projected_quantity de una línea no es regular_quantity + late_quantity.',
    applicability: 'projected_demand_lines',
    sourceTables: ['projected_demand_lines'],
    expectedInvariant: 'projected_quantity = regular_quantity + late_quantity',
    findingEvidence: '{projectedDemandLineId, projectedQuantity, regularQuantity, lateQuantity}',
    recommendedAction:
      'Inspeccionar la materialización. No reconsolidar automáticamente desde reconciliación.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEM-002',
    version: V,
    domain: 'DEMAND',
    category: 'RECONCILIATION',
    defaultSeverity: 'ERROR',
    description:
      'Las sumas de demand_sources no coinciden con regular/late de la línea materializada.',
    applicability: 'projected_demand_lines con demand_sources',
    sourceTables: ['projected_demand_lines', 'demand_sources'],
    expectedInvariant:
      'SUM(sources REGULAR/LATE) = regular_quantity/late_quantity de la misma revisión',
    findingEvidence:
      '{projectedDemandLineId, expectedRegular, actualRegular, expectedLate, actualLate}',
    recommendedAction: 'Comparar fuentes vs línea. No borrar fuentes para cuadrar.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEM-003',
    version: V,
    domain: 'DEMAND',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'El período/bucket efectivo de una demand_source no sigue las reglas ESP-004.',
    applicability: 'demand_sources',
    sourceTables: ['demand_sources', 'patient_schedules', 'patient_schedule_history'],
    expectedInvariant:
      'ON_TIME → original+REGULAR; LATE+COMPLEMENTARY → original+LATE; LATE+NEXT_PERIOD → deferred+REGULAR',
    findingEvidence:
      '{demandSourceId, scheduleTiming, lateHandling, demandBucket, planningPeriodId}',
    recommendedAction: 'Revisar clasificación ESP-004. No reclasificar fuentes durante el scan.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEM-004',
    version: V,
    domain: 'DEMAND',
    category: 'OBSERVATION',
    defaultSeverity: 'WARNING',
    description:
      'Las programaciones actuales cambiaron después de la última consolidación (proyección stale).',
    applicability: 'projected_demand_lines con schedules activos del mismo período efectivo',
    sourceTables: ['projected_demand_lines', 'demand_sources', 'patient_schedules'],
    expectedInvariant: 'La materialización puede quedar stale; no es corrupción',
    findingEvidence: '{projectedDemandLineId, consolidatedAt, staleReason}',
    recommendedAction:
      'Evaluar si hace falta reconsolidar demanda. No tratar este hallazgo como corrupción de datos.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-PO-001',
    version: V,
    domain: 'PURCHASE',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Línea de OC con requested_quantity <= 0.',
    applicability: 'purchase_order_lines',
    sourceTables: ['purchase_order_lines'],
    expectedInvariant: 'requested_quantity > 0',
    findingEvidence: '{purchaseOrderLineId, requestedQuantity}',
    recommendedAction: 'Inspeccionar la línea. No ajustar cantidades desde reconciliación.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-PO-002',
    version: V,
    domain: 'PURCHASE',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'accepted_quantity negativa o mayor que requested_quantity.',
    applicability: 'purchase_order_lines con accepted_quantity no nula',
    sourceTables: ['purchase_order_lines'],
    expectedInvariant: '0 <= accepted_quantity <= requested_quantity',
    findingEvidence: '{purchaseOrderLineId, acceptedQuantity, requestedQuantity}',
    recommendedAction: 'Revisar la aceptación OLP. No recortar accepted para cuadrar.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-PO-003',
    version: V,
    domain: 'PURCHASE',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Allocation con allocated_quantity <= 0.',
    applicability: 'purchase_order_demand_allocations',
    sourceTables: ['purchase_order_demand_allocations'],
    expectedInvariant: 'allocated_quantity > 0',
    findingEvidence: '{purchaseOrderLineId, allocatedQuantity}',
    recommendedAction:
      'Revisar allocations. Over-order posterior a una baja de demanda no es este hallazgo.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-PO-004',
    version: V,
    domain: 'PURCHASE',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'Bucket de allocation incompatible con el tipo de OC ESP-005.',
    applicability: 'purchase_order_demand_allocations unidas a purchase_orders',
    sourceTables: ['purchase_order_demand_allocations', 'purchase_order_lines', 'purchase_orders'],
    expectedInvariant: 'STANDARD → REGULAR; COMPLEMENTARY → LATE',
    findingEvidence: '{purchaseOrderId, orderType, demandBucket}',
    recommendedAction: 'Verificar tipo de OC vs bucket. No reetiquetar allocations.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-PO-005',
    version: V,
    domain: 'PURCHASE',
    category: 'RECONCILIATION',
    defaultSeverity: 'ERROR',
    description:
      'Effective coverage persistida no coincide con la fórmula ESP-005. Si solo es read model, no hay finding de DB.',
    applicability: 'No hay snapshot persistido de effective coverage',
    sourceTables: [],
    expectedInvariant:
      'La cobertura efectiva se calcula en query (ESP-013); no hay materialización que reconciliar',
    findingEvidence: 'n/a',
    recommendedAction:
      'Cubrir la fórmula con tests de servicio. No inventar findings de cobertura.',
    detectionMode: 'RUNTIME_CONTRACT',
    executable: false,
  }),
  define({
    ruleCode: 'REC-PO-006',
    version: V,
    domain: 'PURCHASE',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'Línea de OC referencia una projected demand revision que ya no existe.',
    applicability: 'purchase_order_lines.projected_demand_line_id',
    sourceTables: ['purchase_order_lines', 'projected_demand_lines'],
    expectedInvariant:
      'El id histórico puede sobrevivir a una proyección reemplazada; el finding aplica si no existe ninguna línea con ese id',
    findingEvidence: '{purchaseOrderLineId, projectedDemandLineId, projectedDemandRevision}',
    recommendedAction:
      'Confirmar si la proyección fue reemplazada (histórico válido) o el id es huérfano real.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEL-001',
    version: V,
    domain: 'DELIVERY',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Suma de cantidades DISPATCHED por línea de OC supera accepted_quantity.',
    applicability: 'delivery_lines de deliveries DISPATCHED/RECEIVED',
    sourceTables: ['deliveries', 'delivery_lines', 'purchase_order_lines'],
    expectedInvariant: 'SUM(dispatched) <= accepted_quantity de la PO line',
    findingEvidence: '{purchaseOrderLineId, dispatchedSum, acceptedQuantity}',
    recommendedAction:
      'Revisar despachos vs aceptación. No crear entregas inversas desde reconciliación.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEL-002',
    version: V,
    domain: 'DELIVERY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Delivery DISPATCHED sin líneas.',
    applicability: 'deliveries.status = DISPATCHED o RECEIVED',
    sourceTables: ['deliveries', 'delivery_lines'],
    expectedInvariant: 'Un despacho confirmado tiene al menos una línea',
    findingEvidence: '{deliveryId, status, lineCount}',
    recommendedAction: 'Inspeccionar la entrega. No insertar líneas ficticias.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEL-003',
    version: V,
    domain: 'DELIVERY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Delivery line con quantity <= 0.',
    applicability: 'delivery_lines',
    sourceTables: ['delivery_lines'],
    expectedInvariant: 'quantity > 0',
    findingEvidence: '{deliveryLineId, quantity}',
    recommendedAction: 'Revisar la línea de despacho. No corregir la cantidad automáticamente.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-DEL-004',
    version: V,
    domain: 'DELIVERY',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'Delivery line apunta a una PO line de producto o punto incompatibles.',
    applicability: 'delivery_lines',
    sourceTables: ['delivery_lines', 'purchase_order_lines'],
    expectedInvariant: 'commercial_code y dispensing_point_id coinciden con la PO line',
    findingEvidence:
      '{deliveryLineId, purchaseOrderLineId, deliveryCode, poCode, deliveryPointId, poPointId}',
    recommendedAction: 'Comparar delivery_lines vs purchase_order_lines. No reasignar el despacho.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-RCP-001',
    version: V,
    domain: 'RECEIPT',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'En un receipt confirmado, accepted + rejected no iguala received.',
    applicability: 'receipt_lines de receipts CONFIRMED',
    sourceTables: ['receipts', 'receipt_lines'],
    expectedInvariant: 'accepted_quantity + rejected_quantity = received_quantity',
    findingEvidence: '{receiptLineId, acceptedQuantity, rejectedQuantity, receivedQuantity}',
    recommendedAction: 'Revisar cantidades observadas. No recalcular received.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-RCP-002',
    version: V,
    domain: 'RECEIPT',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'shortage_quantity no es dispatched - received.',
    applicability: 'receipt_lines',
    sourceTables: ['receipt_lines'],
    expectedInvariant: 'shortage_quantity = dispatched_quantity - received_quantity',
    findingEvidence: '{receiptLineId, shortageQuantity, dispatchedQuantity, receivedQuantity}',
    recommendedAction: 'Revisar faltante. No completar el faltante con stock inventado.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-RCP-003',
    version: V,
    domain: 'RECEIPT',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'received_quantity > dispatched_quantity (over-receipt prohibido).',
    applicability: 'receipt_lines',
    sourceTables: ['receipt_lines'],
    expectedInvariant: 'received_quantity <= dispatched_quantity',
    findingEvidence: '{receiptLineId, receivedQuantity, dispatchedQuantity}',
    recommendedAction: 'Investigar over-receipt. No reducir received para ocultar el exceso.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-RCP-004',
    version: V,
    domain: 'RECEIPT',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'accepted_quantity > 0 sin lote/vencimiento observados requeridos.',
    applicability: 'receipt_lines con accepted_quantity > 0',
    sourceTables: ['receipt_lines', 'receipts'],
    expectedInvariant: 'accepted > 0 exige received_lot_number y received_expiration_date',
    findingEvidence: '{receiptLineId, acceptedQuantity, receivedLotNumber, receivedExpirationDate}',
    recommendedAction: 'Revisar la recepción confirmada. No inventar lote observado.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-RCP-005',
    version: V,
    domain: 'RECEIPT',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Receipt CONFIRMED mutable después de confirmación. Solo si hay evidencia fiable de auditoría de campos.',
    applicability: 'No hay historial de campos de receipt_lines',
    sourceTables: ['receipts'],
    expectedInvariant: 'Sin evidence de mutación post-confirmación no se emite finding',
    findingEvidence: 'n/a',
    recommendedAction: 'No inferir mutación solo por updated_at.',
    detectionMode: 'NOT_IMPLEMENTED_NO_EVIDENCE',
    executable: false,
  }),
  define({
    ruleCode: 'REC-INV-001',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Cada receipt_line CONFIRMED con accepted_quantity > 0 debe tener exactamente un movement RECEIPT.',
    applicability: 'receipt_lines de receipts CONFIRMED con accepted_quantity > 0',
    sourceTables: ['receipts', 'receipt_lines', 'inventory_movements'],
    expectedInvariant:
      'exactamente 1 RECEIPT / RECEIPT_LINE / source_id = receipt_line.id / delta = +accepted',
    findingEvidence:
      '{receiptLineId, expectedMovementCount, actualMovementCount, expectedDelta, actualDelta}',
    recommendedAction:
      'Revisar receipt_line y movements RECEIPT. No crear el movimiento faltante sin análisis.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-002',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Movement RECEIPT debe ser positivo.',
    applicability: 'inventory_movements.movement_type = RECEIPT',
    sourceTables: ['inventory_movements'],
    expectedInvariant: 'quantity_delta > 0',
    findingEvidence: '{inventoryMovementId, quantityDelta}',
    recommendedAction: 'Inspeccionar el ledger. No invertir el signo automáticamente.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-003',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Movement APPLICATION debe ser negativo.',
    applicability: 'inventory_movements.movement_type = APPLICATION',
    sourceTables: ['inventory_movements'],
    expectedInvariant: 'quantity_delta < 0',
    findingEvidence: '{inventoryMovementId, quantityDelta}',
    recommendedAction: 'Inspeccionar el ledger. No invertir el signo automáticamente.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-004',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'TRANSFER_OUT debe ser negativo.',
    applicability: 'inventory_movements.movement_type = TRANSFER_OUT',
    sourceTables: ['inventory_movements'],
    expectedInvariant: 'quantity_delta < 0',
    findingEvidence: '{inventoryMovementId, quantityDelta}',
    recommendedAction: 'Revisar el traslado en origen. No crear TRANSFER_IN compensatorio.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-005',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'TRANSFER_IN debe ser positivo.',
    applicability: 'inventory_movements.movement_type = TRANSFER_IN',
    sourceTables: ['inventory_movements'],
    expectedInvariant: 'quantity_delta > 0',
    findingEvidence: '{inventoryMovementId, quantityDelta}',
    recommendedAction: 'Revisar el traslado en destino.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-006',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'NON_REUSABLE debe ser negativo.',
    applicability: 'inventory_movements.movement_type = NON_REUSABLE',
    sourceTables: ['inventory_movements'],
    expectedInvariant: 'quantity_delta < 0',
    findingEvidence: '{inventoryMovementId, quantityDelta}',
    recommendedAction: 'Revisar el outcome NON_REUSABLE y el movement asociado.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-007',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Identidad de lote duplicada (commercial_code, punto, lot_number, expiration_date).',
    applicability: 'inventory_lots',
    sourceTables: ['inventory_lots'],
    expectedInvariant: 'UNIQUE (commercial_code, dispensing_point_id, lot_number, expiration_date)',
    findingEvidence: '{commercialCode, dispensingPointId, lotNumber, expirationDate, lotCount}',
    recommendedAction: 'Investigar lotes duplicados. No fusionar saldos automáticamente.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-008',
    version: V,
    domain: 'INVENTORY',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'physicalBalance derivado del ledger es negativo. usableBalance 0 por vencimiento no es esto.',
    applicability: 'inventory_lots con movements',
    sourceTables: ['inventory_lots', 'inventory_movements'],
    expectedInvariant: 'SUM(quantity_delta) >= 0',
    findingEvidence: '{inventoryLotId, physicalBalance}',
    recommendedAction:
      'Reconstruir el ledger del lote. No confundir vencimiento (usable 0) con balance físico negativo.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-INV-009',
    version: V,
    domain: 'INVENTORY',
    category: 'OBSERVATION',
    defaultSeverity: 'INFO',
    description: 'Existe inventario físico expirado con usableBalance 0.',
    applicability: 'inventory_lots con expiration_date < current_date y physicalBalance > 0',
    sourceTables: ['inventory_lots', 'inventory_movements'],
    expectedInvariant: 'Condición operacional válida; no es corrupción',
    findingEvidence: '{inventoryLotId, physicalBalance, expirationDate}',
    recommendedAction:
      'Gestionar stock vencido por el flujo operacional. INFO no falla el release gate.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-TRF-001',
    version: V,
    domain: 'TRANSFER',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Cada transfer_line de un transfer DISPATCHED/RECEIVED debe tener exactamente un TRANSFER_OUT.',
    applicability: 'stock_transfer_lines de transfers DISPATCHED o RECEIVED',
    sourceTables: ['stock_transfers', 'stock_transfer_lines', 'inventory_movements'],
    expectedInvariant: 'exactamente 1 TRANSFER_OUT por línea despachada',
    findingEvidence: '{stockTransferLineId, status, transferOutCount}',
    recommendedAction: 'Revisar la línea de traslado y el movement TRANSFER_OUT.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-TRF-002',
    version: V,
    domain: 'TRANSFER',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Cada transfer_line de un transfer RECEIVED debe tener exactamente un TRANSFER_IN.',
    applicability: 'stock_transfer_lines de transfers RECEIVED',
    sourceTables: ['stock_transfers', 'stock_transfer_lines', 'inventory_movements'],
    expectedInvariant: 'exactamente 1 TRANSFER_IN por línea recibida',
    findingEvidence: '{stockTransferLineId, transferInCount}',
    recommendedAction: 'Revisar recepción del traslado. No insertar TRANSFER_IN sin análisis.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-TRF-003',
    version: V,
    domain: 'TRANSFER',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Transfer DISPATCHED con TRANSFER_IN antes de RECEIVE.',
    applicability: 'stock_transfers.status = DISPATCHED',
    sourceTables: ['stock_transfers', 'stock_transfer_lines', 'inventory_movements'],
    expectedInvariant: 'DISPATCHED no debe tener TRANSFER_IN',
    findingEvidence: '{stockTransferId, transferInCount}',
    recommendedAction: 'Investigar movements TRANSFER_IN prematuros.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-TRF-004',
    version: V,
    domain: 'TRANSFER',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Origen y destino del traslado son el mismo punto.',
    applicability: 'stock_transfers',
    sourceTables: ['stock_transfers'],
    expectedInvariant: 'source_dispensing_point_id <> destination_dispensing_point_id',
    findingEvidence: '{stockTransferId, sourceDispensingPointId, destinationDispensingPointId}',
    recommendedAction: 'Revisar el traslado. No reescribir puntos.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-TRF-005',
    version: V,
    domain: 'TRANSFER',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Conservación por traslado RECEIVED: abs(TRANSFER_OUT) = TRANSFER_IN por línea.',
    applicability: 'stock_transfers.status = RECEIVED',
    sourceTables: ['stock_transfers', 'stock_transfer_lines', 'inventory_movements'],
    expectedInvariant: 'abs(out.delta) = in.delta = line.quantity',
    findingEvidence: '{stockTransferLineId, outDelta, inDelta, lineQuantity}',
    recommendedAction:
      'Revisar OUT/IN del traslado. No inventar una ecuación global de inventario.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-TRF-006',
    version: V,
    domain: 'TRANSFER',
    category: 'OBSERVATION',
    defaultSeverity: 'INFO',
    description:
      'Transfer DISPATCHED con TRANSFER_OUT y sin TRANSFER_IN es el estado normal en tránsito. No genera finding.',
    applicability: 'stock_transfers.status = DISPATCHED',
    sourceTables: ['stock_transfers', 'stock_transfer_lines', 'inventory_movements'],
    expectedInvariant: 'DISPATCHED + OUT + !IN es válido',
    findingEvidence: 'n/a — evaluado para demostrar ausencia de falso positivo',
    recommendedAction: 'Ninguna. El stock en tránsito no es un error.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-APP-001',
    version: V,
    domain: 'APPLICATION',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'patient_application CONFIRMED sin application lines.',
    applicability: 'patient_applications.status = CONFIRMED',
    sourceTables: ['patient_applications', 'patient_application_lines'],
    expectedInvariant: 'CONFIRMED tiene al menos una línea',
    findingEvidence: '{patientApplicationId, lineCount}',
    recommendedAction: 'Revisar la aplicación confirmada. No crear líneas ficticias.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-APP-002',
    version: V,
    domain: 'APPLICATION',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Suma de application_lines.quantity no coincide con la quantity de la schedule revision confirmada.',
    applicability: 'patient_applications CONFIRMED',
    sourceTables: ['patient_applications', 'patient_application_lines', 'patient_schedule_history'],
    expectedInvariant: 'SUM(lines.quantity) = schedule history quantity de la revision confirmada',
    findingEvidence: '{patientApplicationId, appliedSum, scheduleQuantity, scheduleRevision}',
    recommendedAction: 'Comparar líneas vs snapshot de programación. No ajustar cantidades.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-APP-003',
    version: V,
    domain: 'APPLICATION',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Cada application_line de CONFIRMED debe tener exactamente un APPLICATION movement.',
    applicability: 'patient_application_lines de applications CONFIRMED',
    sourceTables: ['patient_applications', 'patient_application_lines', 'inventory_movements'],
    expectedInvariant: 'exactamente 1 APPLICATION / APPLICATION_LINE / source_id = line.id',
    findingEvidence: '{applicationLineId, expectedMovementCount, actualMovementCount}',
    recommendedAction:
      'Revisar application_line y movement APPLICATION. No crear movimiento manualmente sin análisis.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-APP-004',
    version: V,
    domain: 'APPLICATION',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'abs(APPLICATION.quantity_delta) debe igualar application_line.quantity.',
    applicability: 'application lines CONFIRMED con movement APPLICATION',
    sourceTables: ['patient_application_lines', 'inventory_movements'],
    expectedInvariant: 'abs(delta) = line.quantity',
    findingEvidence: '{applicationLineId, lineQuantity, quantityDelta}',
    recommendedAction: 'Comparar cantidad de línea vs ledger. No ajustar el delta.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-APP-005',
    version: V,
    domain: 'APPLICATION',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Lote de application_line incompatible con producto/punto de la aplicación/schedule.',
    applicability: 'patient_application_lines',
    sourceTables: ['patient_application_lines', 'patient_applications', 'inventory_lots'],
    expectedInvariant:
      'line.commercial_code y dispensing_point_id coinciden con application y lote',
    findingEvidence:
      '{applicationLineId, lineCode, applicationCode, lotCode, linePointId, applicationPointId}',
    recommendedAction: 'Revisar el lote aplicado vs la programación. No reasignar lotes.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-APP-006',
    version: V,
    domain: 'APPLICATION',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Aplicación CONFIRMED y outcome NOT_APPLIED coexisten para la misma schedule revision.',
    applicability: 'patient_applications CONFIRMED cruzadas con patient_schedule_outcomes',
    sourceTables: ['patient_applications', 'patient_schedule_outcomes'],
    expectedInvariant: 'Una revision no puede ser APPLIED (CONFIRMED) y NOT_APPLIED a la vez',
    findingEvidence: '{patientScheduleId, scheduleRevision, patientApplicationId, outcomeId}',
    recommendedAction:
      'Investigar aplicación vs outcome. Ownership de este invariante: REC-APP-006 (no REC-OUT-002).',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-OUT-001',
    version: V,
    domain: 'OUTCOME',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Más de un NOT_APPLIED terminal para la misma schedule_id + revision.',
    applicability: 'patient_schedule_outcomes',
    sourceTables: ['patient_schedule_outcomes'],
    expectedInvariant: 'UNIQUE (patient_schedule_id, schedule_revision)',
    findingEvidence: '{patientScheduleId, scheduleRevision, outcomeCount}',
    recommendedAction: 'Investigar outcomes duplicados. No borrar el sobrante automáticamente.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-OUT-002',
    version: V,
    domain: 'OUTCOME',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'NOT_APPLIED y CONFIRMED coexistiendo. Ownership: REC-APP-006.',
    applicability: 'Cubierto por REC-APP-006',
    sourceTables: ['patient_applications', 'patient_schedule_outcomes'],
    expectedInvariant: 'No duplicar el finding de REC-APP-006',
    findingEvidence: 'n/a',
    recommendedAction: 'Ver REC-APP-006.',
    detectionMode: 'OWNED_BY_OTHER',
    ownedBy: 'REC-APP-006',
    executable: false,
  }),
  define({
    ruleCode: 'REC-OUT-003',
    version: V,
    domain: 'OUTCOME',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Outcome line NON_REUSABLE sin exactamente un movement NON_REUSABLE.',
    applicability: 'patient_schedule_outcome_lines de outcomes NON_REUSABLE',
    sourceTables: [
      'patient_schedule_outcomes',
      'patient_schedule_outcome_lines',
      'inventory_movements',
    ],
    expectedInvariant: 'exactamente 1 NON_REUSABLE movement por outcome line',
    findingEvidence: '{outcomeLineId, movementCount}',
    recommendedAction:
      'Revisar outcome line y movement NON_REUSABLE. No crear el movement faltante sin análisis.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-OUT-004',
    version: V,
    domain: 'OUTCOME',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'NON_REUSABLE movement quantity no coincide con la outcome line.',
    applicability: 'outcome lines NON_REUSABLE con movement',
    sourceTables: ['patient_schedule_outcome_lines', 'inventory_movements'],
    expectedInvariant: 'abs(delta) = outcome_line.quantity',
    findingEvidence: '{outcomeLineId, lineQuantity, quantityDelta}',
    recommendedAction: 'Comparar cantidades. No ajustar el ledger.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-OUT-005',
    version: V,
    domain: 'OUTCOME',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'REUSABLE o NOT_PREPARED generó movement de stock asociado.',
    applicability: 'patient_schedule_outcomes con disposition REUSABLE o NOT_PREPARED',
    sourceTables: [
      'patient_schedule_outcomes',
      'patient_schedule_outcome_lines',
      'inventory_movements',
    ],
    expectedInvariant: 'REUSABLE/NOT_PREPARED no produce NON_REUSABLE (ni otro) movement de stock',
    findingEvidence: '{outcomeId, preparedProductDisposition, movementCount}',
    recommendedAction:
      'Investigar movements huérfanos ligados al outcome. No revertir stock automáticamente.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-OUT-006',
    version: V,
    domain: 'OUTCOME',
    category: 'INTEGRITY',
    defaultSeverity: 'ERROR',
    description: 'Suma de nonReusableLines.quantity supera la quantity de la schedule.',
    applicability: 'outcomes NON_REUSABLE',
    sourceTables: [
      'patient_schedule_outcomes',
      'patient_schedule_outcome_lines',
      'patient_schedule_history',
    ],
    expectedInvariant: 'SUM(nonReusableLines.quantity) <= schedule quantity',
    findingEvidence: '{outcomeId, nonReusableSum, scheduleQuantity}',
    recommendedAction: 'Revisar líneas NON_REUSABLE vs snapshot de programación.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-AUD-001',
    version: V,
    domain: 'AUDIT',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'patient_application_audit APPROVED con admission_status distinto de READY.',
    applicability: 'patient_application_audits.status = APPROVED (lineage moderno)',
    sourceTables: ['patient_application_audits', 'patient_applications', 'authorization_items'],
    expectedInvariant: 'APPROVED implica admission_status READY',
    findingEvidence: '{patientApplicationAuditId, admissionStatus}',
    recommendedAction: 'Investigar auditoría vs admisión. No poner READY para ocultar el hallazgo.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-AUD-002',
    version: V,
    domain: 'AUDIT',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'admission_status READY sin patient_application_audit APPROVED correspondiente.',
    applicability: 'authorization_items.admission_status = READY',
    sourceTables: ['authorization_items', 'patient_application_audits', 'patient_applications'],
    expectedInvariant: 'READY exige auditoría moderna APPROVED de una application CONFIRMED',
    findingEvidence: '{authorizationItemId, approvedAuditCount}',
    recommendedAction:
      'Investigar admisión READY. Ownership: REC-AUD-002 (no duplicar con REC-LEG-003).',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-AUD-003',
    version: V,
    domain: 'AUDIT',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Audit REJECTED con admission_status READY atribuible a esa application.',
    applicability: 'patient_application_audits.status = REJECTED',
    sourceTables: ['patient_application_audits', 'patient_applications', 'authorization_items'],
    expectedInvariant: 'REJECTED no produce READY',
    findingEvidence: '{patientApplicationAuditId, authorizationItemId, admissionStatus}',
    recommendedAction:
      'REJECTED no implica NOT_APPLIED. Investigar por qué admission quedó READY. No crear outcome.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-AUD-004',
    version: V,
    domain: 'AUDIT',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'Existe audit para una patient_application que no está CONFIRMED.',
    applicability: 'patient_application_audits',
    sourceTables: ['patient_application_audits', 'patient_applications'],
    expectedInvariant: 'La application auditada está CONFIRMED',
    findingEvidence: '{patientApplicationAuditId, patientApplicationId, applicationStatus}',
    recommendedAction: 'Revisar la application asociada. No confirmarla para ocultar el hallazgo.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-AUD-005',
    version: V,
    domain: 'AUDIT',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Más de una audit por application.',
    applicability: 'patient_application_audits',
    sourceTables: ['patient_application_audits'],
    expectedInvariant: 'UNIQUE (patient_application_id)',
    findingEvidence: '{patientApplicationId, auditCount}',
    recommendedAction: 'Investigar audits duplicadas.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-AUD-006',
    version: V,
    domain: 'AUDIT',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Audit APPROVED/REJECTED modificable después de terminal. Solo si existe historial de campos.',
    applicability: 'Sin tabla de history de audits más allá del trigger de inmutabilidad',
    sourceTables: ['patient_application_audits'],
    expectedInvariant: 'Sin evidence de mutación post-terminal no se emite finding',
    findingEvidence: 'n/a',
    recommendedAction: 'El trigger de inmutabilidad es la prevención. No inventar history.',
    detectionMode: 'NOT_IMPLEMENTED_NO_EVIDENCE',
    executable: false,
  }),
  define({
    ruleCode: 'REC-ANA-001',
    version: V,
    domain: 'ANALYTICS',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Projected tariff histórica aparece EXACT usando la tarifa activa actual sin PERIOD_EFFECTIVE_TARIFF lineage.',
    applicability: 'Métrica calculada en runtime; no hay fila persistida que reconciliar',
    sourceTables: [],
    expectedInvariant: 'projectedTariffReferenceMetric usa PERIOD_EFFECTIVE_TARIFF o UNAVAILABLE',
    findingEvidence: 'n/a — test de servicio',
    recommendedAction: 'Cubrir con tests del servicio analytics. No persistir tarifa inventada.',
    detectionMode: 'RUNTIME_CONTRACT',
    executable: false,
  }),
  define({
    ruleCode: 'REC-ANA-002',
    version: V,
    domain: 'ANALYTICS',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'appliedSupplierCost aparece EXACT sin cost-layer/provenance autorizada.',
    applicability: 'Métrica calculada en runtime',
    sourceTables: [],
    expectedInvariant: 'appliedSupplierCostMetric es UNAVAILABLE (AMBIGUOUS_LOT_PROVENANCE)',
    findingEvidence: 'n/a — test de servicio',
    recommendedAction: 'No fabricar costo aplicado exacto.',
    detectionMode: 'RUNTIME_CONTRACT',
    executable: false,
  }),
  define({
    ruleCode: 'REC-ANA-003',
    version: V,
    domain: 'ANALYTICS',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'UNAVAILABLE serializado como 0.',
    applicability: 'Contrato analytics / export',
    sourceTables: [],
    expectedInvariant: 'UNAVAILABLE → value null, nunca 0',
    findingEvidence: 'n/a — test contractual',
    recommendedAction: 'Mantener el contrato UNAVAILABLE. No convertir a cero.',
    detectionMode: 'RUNTIME_CONTRACT',
    executable: false,
  }),
  define({
    ruleCode: 'REC-BULK-001',
    version: V,
    domain: 'BULK',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'bulk_import_row SUCCEEDED sin entity_reference.',
    applicability: 'bulk_import_rows.execution_status = SUCCEEDED',
    sourceTables: ['bulk_import_rows'],
    expectedInvariant: 'SUCCEEDED tiene entity_reference',
    findingEvidence: '{bulkImportRowId, jobId}',
    recommendedAction: 'Revisar la fila y el schedule creado. No reejecutar SUCCEEDED.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-BULK-002',
    version: V,
    domain: 'BULK',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description:
      'Fila SUCCEEDED de scheduling cuyo entity_reference no apunta a un patient_schedule existente.',
    applicability: 'bulk_import_rows SUCCEEDED de jobs SCHEDULING',
    sourceTables: ['bulk_import_rows', 'bulk_import_jobs', 'patient_schedules'],
    expectedInvariant: 'entity_reference ∈ patient_schedules.id',
    findingEvidence: '{bulkImportRowId, entityReference}',
    recommendedAction:
      'Investigar la referencia huérfana. No recrear el schedule desde reconciliación.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-BULK-003',
    version: V,
    domain: 'BULK',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Fila SUCCEEDED cuyo schedule no corresponde al payload normalizado determinista (sin PHI).',
    applicability: 'bulk_import_rows SUCCEEDED con entity_reference y normalized_payload',
    sourceTables: ['bulk_import_rows', 'patient_schedules'],
    expectedInvariant:
      'commercialCode, scheduledDate, dispensingPoint y quantity del payload coinciden con el schedule',
    findingEvidence: '{bulkImportRowId, patientScheduleId, mismatchedFields}',
    recommendedAction:
      'Comparar payload normalizado vs schedule. No incluir nombres ni documentos en evidence.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-BULK-004',
    version: V,
    domain: 'BULK',
    category: 'OBSERVATION',
    defaultSeverity: 'WARNING',
    description:
      'Row PROCESSING con claim_expires_at vencido (RECOVERABLE_STALE_CLAIM). No es corrupción.',
    applicability: 'bulk_import_rows.execution_status = PROCESSING',
    sourceTables: ['bulk_import_rows'],
    expectedInvariant: 'Lease expirado es recuperable',
    findingEvidence: '{bulkImportRowId, claimExpiresAt, staleClaim: true}',
    recommendedAction: 'Reanudar o recuperar el claim por el flujo bulk. No marcarlo corrupción.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-BULK-005',
    version: V,
    domain: 'BULK',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'Job COMPLETED con alguna row distinta de SUCCEEDED/SKIPPED.',
    applicability: 'bulk_import_jobs.status = COMPLETED',
    sourceTables: ['bulk_import_jobs', 'bulk_import_rows'],
    expectedInvariant: 'COMPLETED solo admite SUCCEEDED o SKIPPED en execution_status',
    findingEvidence: '{bulkImportJobId, offendingRowId, executionStatus}',
    recommendedAction:
      'Revisar el cierre del job. No cambiar el status del job desde reconciliación.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-BULK-006',
    version: V,
    domain: 'BULK',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Job PARTIALLY_COMPLETED sin mezcla compatible de resultados (succeeded>0 y failed>0).',
    applicability: 'bulk_import_jobs.status = PARTIALLY_COMPLETED',
    sourceTables: ['bulk_import_jobs', 'bulk_import_rows'],
    expectedInvariant: 'PARTIALLY_COMPLETED = al menos un SUCCEEDED y al menos un FAILED',
    findingEvidence: '{bulkImportJobId, succeededRows, failedRows}',
    recommendedAction: 'Revisar decideBulkImportCompletion. No reescribir el status.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-BULK-007',
    version: V,
    domain: 'BULK',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Fila SUCCEEDED ejecutada más de una vez según attempts/provenance.',
    applicability: 'bulk_import_row_attempts con status SUCCEEDED',
    sourceTables: ['bulk_import_rows', 'bulk_import_row_attempts'],
    expectedInvariant: 'A lo sumo un attempt SUCCEEDED por row',
    findingEvidence: '{bulkImportRowId, succeededAttemptCount}',
    recommendedAction: 'Investigar reejecución. Retry no debe reejecutar SUCCEEDED.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCOPE-001',
    version: V,
    domain: 'SCOPE',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'Dos grants activos idénticos user+point.',
    applicability: 'user_point_scopes con revoked_at IS NULL',
    sourceTables: ['user_point_scopes'],
    expectedInvariant: 'UNIQUE activo (user_id, dispensing_point_id)',
    findingEvidence: '{userId, dispensingPointId, activeGrantCount}',
    recommendedAction: 'Investigar grants duplicados. No revocar automáticamente.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCOPE-002',
    version: V,
    domain: 'SCOPE',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description: 'Grant activo hacia dispensing point inexistente.',
    applicability: 'user_point_scopes activos',
    sourceTables: ['user_point_scopes', 'dispensing_points'],
    expectedInvariant: 'dispensing_point_id referencia un punto existente',
    findingEvidence: '{userPointScopeId, dispensingPointId}',
    recommendedAction: 'Revisar la FK. No borrar el grant.',
    detectionMode: 'BOTH',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCOPE-003',
    version: V,
    domain: 'SCOPE',
    category: 'OBSERVATION',
    defaultSeverity: 'WARNING',
    description:
      'Grant activo hacia un punto hoy inactivo. Puede ser histórico válido (el punto se desactivó después).',
    applicability: 'user_point_scopes activos join dispensing_points.active = false',
    sourceTables: ['user_point_scopes', 'dispensing_points'],
    expectedInvariant: 'No es corrupción por sí solo',
    findingEvidence: '{userPointScopeId, dispensingPointId, pointActive}',
    recommendedAction: 'Confirmar si el grant debe revocarse operativamente. No asumir corrupción.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCOPE-004',
    version: V,
    domain: 'SCOPE',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Grant Medicarte hacia un punto que no pertenece al dominio organizacional permitido.',
    applicability: 'grants activos a usuarios MEDICARTE_OPERATOR',
    sourceTables: [
      'user_point_scopes',
      'dispensing_points',
      'users',
      'user_organization_roles',
      'roles',
    ],
    expectedInvariant: 'El punto pertenece a la organización MEDICARTE',
    findingEvidence: '{userPointScopeId, dispensingPointId, pointOrganizationId}',
    recommendedAction: 'Revisar el punto y el grant. No reasignar organization_id del punto.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-SCOPE-005',
    version: V,
    domain: 'SCOPE',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'Grant Medicarte creado por un actor que hoy no tiene rol MTD_ADMIN (si el trail lo demuestra).',
    applicability: 'user_point_scopes.granted_by',
    sourceTables: ['user_point_scopes', 'users', 'user_organization_roles', 'roles'],
    expectedInvariant: 'granted_by tiene rol MTD_ADMIN en MTD',
    findingEvidence: '{userPointScopeId, grantedBy}',
    recommendedAction:
      'Verificar el actor otorgante. Un rol revocado después puede ser falso positivo; contrastar con users.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-LEG-001',
    version: V,
    domain: 'LEGACY',
    category: 'OBSERVATION',
    defaultSeverity: 'ERROR',
    description:
      'El runtime moderno depende de un leftover legacy. Se incorpora el scanner ESP-016 como metadata de release.',
    applicability: 'Release/CLI con --legacy-scan; no inspecciona PostgreSQL',
    sourceTables: [],
    expectedInvariant: 'check-legacy-operational-usage PASS',
    findingEvidence: '{scanStatus, hitCount} sin PHI ni payloads',
    recommendedAction:
      'Corregir usos leftover en código. No mutar columnas legacy para “arreglar” el scan.',
    detectionMode: 'RUNTIME_CONTRACT',
    executable: true,
  }),
  define({
    ruleCode: 'REC-LEG-002',
    version: V,
    domain: 'LEGACY',
    category: 'CONSISTENCY',
    defaultSeverity: 'ERROR',
    description:
      'audit_status leftover diverge de la proyección de compatibilidad esperada para una audit moderna.',
    applicability: 'patient_application_audits terminales (APPROVED/REJECTED) con lineage moderno',
    sourceTables: ['patient_application_audits', 'patient_applications', 'authorization_items'],
    expectedInvariant: 'APPROVED → leftover APPROVED; REJECTED → leftover REJECTED',
    findingEvidence: '{patientApplicationAuditId, modernStatus, leftoverAuditStatus}',
    recommendedAction:
      'Investigar LegacyCompatibilityProjectionService. No reescribir leftover para ocultar drift.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
  define({
    ruleCode: 'REC-LEG-003',
    version: V,
    domain: 'LEGACY',
    category: 'INTEGRITY',
    defaultSeverity: 'CRITICAL',
    description: 'READY sin modern APPROVED. Ownership: REC-AUD-002.',
    applicability: 'Cubierto por REC-AUD-002',
    sourceTables: ['authorization_items', 'patient_application_audits'],
    expectedInvariant: 'No duplicar REC-AUD-002',
    findingEvidence: 'n/a',
    recommendedAction: 'Ver REC-AUD-002.',
    detectionMode: 'OWNED_BY_OTHER',
    ownedBy: 'REC-AUD-002',
    executable: false,
  }),
  define({
    ruleCode: 'REC-LEG-004',
    version: V,
    domain: 'LEGACY',
    category: 'OBSERVATION',
    defaultSeverity: 'INFO',
    description:
      'Registro historical-only sin lineage moderno. Es NORMAL: se evalúa y no genera finding.',
    applicability:
      'authorization_items sin patient_schedules ni patient_applications (evidencia estructural, no fecha)',
    sourceTables: ['authorization_items', 'patient_schedules', 'patient_applications'],
    expectedInvariant: 'Historical-only no exige lineage moderno',
    findingEvidence: 'n/a — evaluatedCount > 0 y findingCount = 0',
    recommendedAction: 'Ninguna. No crear patient_application ni OC para filas históricas.',
    detectionMode: 'DETECTABLE_BY_RECONCILIATION',
    executable: true,
  }),
];

export const RECONCILIATION_RULE_BY_CODE: Readonly<Record<string, ReconciliationRuleDefinition>> =
  Object.fromEntries(RECONCILIATION_RULES.map((rule) => [rule.ruleCode, rule]));

export const EXECUTABLE_RECONCILIATION_RULES = RECONCILIATION_RULES.filter(
  (rule) => rule.executable,
);

export const RECONCILIATION_WRITABLE_TABLES = [
  'reconciliation_runs',
  'reconciliation_findings',
  'reconciliation_issues',
  'reconciliation_issue_events',
  'reconciliation_issue_comments',
  'reconciliation_operation_policies',
  'reconciliation_operation_executions',
  'reconciliation_notifications',
] as const;

export const RECONCILIATION_OPERATIONAL_TABLES = [
  'patient_schedules',
  'patient_schedule_history',
  'projected_demand_lines',
  'demand_sources',
  'purchase_orders',
  'purchase_order_lines',
  'purchase_order_demand_allocations',
  'deliveries',
  'delivery_lines',
  'receipts',
  'receipt_lines',
  'inventory_lots',
  'inventory_movements',
  'stock_transfers',
  'stock_transfer_lines',
  'patient_applications',
  'patient_application_lines',
  'patient_application_audits',
  'patient_schedule_outcomes',
  'patient_schedule_outcome_lines',
  'bulk_import_jobs',
  'bulk_import_rows',
  'bulk_import_row_attempts',
  'user_point_scopes',
  'authorization_items',
  'planning_periods',
  'dispensing_points',
] as const;

export function isBlockingReconciliationSeverity(severity: ReconciliationSeverity): boolean {
  return severity === 'CRITICAL' || severity === 'ERROR';
}

export function reconciliationFindingFingerprint(input: {
  ruleCode: string;
  entityType: string;
  entityId: string | null;
  relatedEntityId?: string | null;
}): string {
  return `${input.ruleCode}|${input.entityType}|${input.entityId ?? ''}|${input.relatedEntityId ?? ''}`;
}

export function formatReconciliationRuleCatalog(): string {
  const header = [
    '| RULE CODE | DOMAIN | CATEGORY | SEVERITY | DESCRIPTION | APPLICABILITY | SOURCE TABLES | EXPECTED INVARIANT | FINDING EVIDENCE | PREVENTED_BY_DB? | RECONCILIATION_DETECTABLE? |',
    '| --------- | ------ | -------- | -------- | ----------- | ------------- | ------------- | ------------------ | ---------------- | ---------------- | -------------------------- |',
  ];
  const rows = RECONCILIATION_RULES.map((rule) => {
    const prevented =
      rule.detectionMode === 'PREVENTED_BY_DB' || rule.detectionMode === 'BOTH' ? 'yes' : 'no';
    const detectable =
      rule.detectionMode === 'DETECTABLE_BY_RECONCILIATION' || rule.detectionMode === 'BOTH'
        ? 'yes'
        : rule.detectionMode === 'RUNTIME_CONTRACT'
          ? 'runtime-contract'
          : rule.detectionMode === 'OWNED_BY_OTHER'
            ? `owned-by ${rule.ownedBy}`
            : rule.detectionMode === 'NOT_IMPLEMENTED_NO_EVIDENCE'
              ? 'no-evidence'
              : 'no';
    return `| ${rule.ruleCode} | ${rule.domain} | ${rule.category} | ${rule.defaultSeverity} | ${rule.description.replace(/\|/g, '/')} | ${rule.applicability.replace(/\|/g, '/')} | ${rule.sourceTables.join(', ') || '—'} | ${rule.expectedInvariant.replace(/\|/g, '/')} | ${rule.findingEvidence.replace(/\|/g, '/')} | ${prevented} | ${detectable} |`;
  });
  return [...header, ...rows].join('\n');
}
