/** Encabezados propios del sistema. Los aliases solo son de entrada. */
export const HEADERS = {
  NUMERO_AUTORIZACION: 'NUMERO_AUTORIZACION',
  CLAVE_AUTORIZACION: 'CLAVE_AUTORIZACION',
  CODIGO_COMERCIAL: 'CODIGO_COMERCIAL',
  CODIGO_PRODUCTO: 'CODIGO_PRODUCTO',
  TIPO_IDENTIFICACION: 'TIPO_IDENTIFICACION',
  IDENTIFICACION_PACIENTE: 'IDENTIFICACION_PACIENTE',
  NUMERO_PRESCRIPCION: 'NUMERO_PRESCRIPCION',
  VALOR_CUOTA_MODERADORA: 'VALOR_CUOTA_MODERADORA',
  IDENTIFICADOR_FUENTE: 'IDENTIFICADOR_FUENTE',
  LUGAR_DISPENSACION: 'LUGAR_DISPENSACION',
  FECHA_DISPENSACION: 'FECHA_DISPENSACION',
  FECHA_APLICACION: 'FECHA_APLICACION',
  TARIFA_UNIDAD: 'TARIFA_UNIDAD',
  NUMERO_EXPEDIENTE_INVIMA: 'NUMERO_EXPEDIENTE_INVIMA',
  CONSECUTIVO_INVIMA_PRESENTACION: 'CONSECUTIVO_INVIMA_PRESENTACION',
  DESCRIPCION_GENERICA_MEDICAMENTO: 'DESCRIPCION_GENERICA_MEDICAMENTO',
  DESCRIPCION_COMERCIAL_MEDICAMENTO: 'DESCRIPCION_COMERCIAL_MEDICAMENTO',
  LABORATORIO_MEDICAMENTO: 'LABORATORIO_MEDICAMENTO',
  TIPO_INCLUSION_MEDICAMENTO: 'TIPO_INCLUSION_MEDICAMENTO',
} as const;

export type CanonicalHeader = (typeof HEADERS)[keyof typeof HEADERS];

const aliases: Record<string, CanonicalHeader> = {
  NUMERO_AUTORIZACION: HEADERS.NUMERO_AUTORIZACION,
  COD_COMERCIAL: HEADERS.CODIGO_COMERCIAL,
  CODIGO_COMERCIAL: HEADERS.CODIGO_COMERCIAL,
  CODIGO_MEDICAMENTO: HEADERS.CODIGO_PRODUCTO,
  CODIGO_PRODUCTO: HEADERS.CODIGO_PRODUCTO,
  AUTHORIZATION_KEY: 'CLAVE_AUTORIZACION',
  CLAVE_AUTORIZACION: 'CLAVE_AUTORIZACION',
  NUM_DOCUMENTO: HEADERS.IDENTIFICACION_PACIENTE,
  IDENTIFICACION_PACIENTE: HEADERS.IDENTIFICACION_PACIENTE,
  TIP_DOCUMENTO: HEADERS.TIPO_IDENTIFICACION,
  TIPO_IDENTIFICACION: HEADERS.TIPO_IDENTIFICACION,
  'NO_PRESCRIPCION': HEADERS.NUMERO_PRESCRIPCION,
  'NO.PRESCRIPCION': HEADERS.NUMERO_PRESCRIPCION,
  VALOR_CUOTA_MODERADORA: HEADERS.VALOR_CUOTA_MODERADORA,
  _ID: HEADERS.IDENTIFICADOR_FUENTE,
  IDENTIFICADOR_FUENTE: HEADERS.IDENTIFICADOR_FUENTE,
  LUGAR_DISPENSACION: HEADERS.LUGAR_DISPENSACION,
  FECHA_DISPENSACION: HEADERS.FECHA_DISPENSACION,
  FECHA_APLICACION: HEADERS.FECHA_APLICACION,
  'TARIFA_DE_LA_UNIDAD': HEADERS.TARIFA_UNIDAD,
  'NUMERO_DE_EXPEDIENTE_DEL_INVIMA': HEADERS.NUMERO_EXPEDIENTE_INVIMA,
  'CONSECUTIVO_INVIMA_PRESENTACION': HEADERS.CONSECUTIVO_INVIMA_PRESENTACION,
  'CONSECUTIVO_INVIMA_DE_PRESENTACION': HEADERS.CONSECUTIVO_INVIMA_PRESENTACION,
  'DESCRIPCION_GENERICA_DEL_MEDICAMENTO_DCI': HEADERS.DESCRIPCION_GENERICA_MEDICAMENTO,
  'DESCRIPCION_COMERCIAL_DEL_MEDICAMENTO': HEADERS.DESCRIPCION_COMERCIAL_MEDICAMENTO,
  'LABORATORIO_DEL_MEDICAMENTO': HEADERS.LABORATORIO_MEDICAMENTO,
  'TIPO_DE_INCLUSION_DEL_MEDICAMENTO_PBS_NOPBS': HEADERS.TIPO_INCLUSION_MEDICAMENTO,
};

export function sanitizeHeader(value: unknown): string {
  const text =
    value === null || value === undefined
      ? ''
      : typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean'
        ? `${value}`
        : (JSON.stringify(value) ?? '');
  return text
    .replace(/^\uFEFF/, '')
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/Ñ/g, 'N')
    .replace(/[^A-Z0-9_]+/gi, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();
}

export function canonicalizeHeader(value: unknown): string {
  const sanitized = sanitizeHeader(value);
  return aliases[sanitized] ?? sanitized;
}

export const authorizationSourceColumns = [
  'CODEPS',
  HEADERS.NUMERO_AUTORIZACION,
  HEADERS.TIPO_IDENTIFICACION,
  HEADERS.IDENTIFICACION_PACIENTE,
  'NOMBRE_PACIENTE',
  'NUMERO_TELEFONO',
  'COD_CUPS_PRINCIPAL',
  'CUPS_PRINCIPAL',
  HEADERS.CODIGO_COMERCIAL,
  'CUMS',
  'NIT_PRESTADOR',
  'NOMBRE_PRESTADOR',
  'COD_CUPS_AUTORIZADO',
  'CUPS_AUTORIZADO',
  'CANTIDAD',
  'DOSIS',
  'FECHA_ASIGNACION',
  'FECHA_FINAL_VIGENCIA',
  'ESTADO_AUTORIZACION',
  HEADERS.NUMERO_PRESCRIPCION,
  'OBS_AUTORIZACION',
  'MEDICO_REMITENTE',
  'CMNT',
  HEADERS.IDENTIFICADOR_FUENTE,
  'FPRO',
  HEADERS.VALOR_CUOTA_MODERADORA,
  'CPRG',
  'CDGN001',
] as const;

export const tariffAnnexSourceColumns = [
  HEADERS.CODIGO_PRODUCTO,
  HEADERS.TARIFA_UNIDAD,
  HEADERS.NUMERO_EXPEDIENTE_INVIMA,
  HEADERS.CONSECUTIVO_INVIMA_PRESENTACION,
  HEADERS.DESCRIPCION_GENERICA_MEDICAMENTO,
  HEADERS.DESCRIPCION_COMERCIAL_MEDICAMENTO,
  HEADERS.LABORATORIO_MEDICAMENTO,
  HEADERS.TIPO_INCLUSION_MEDICAMENTO,
] as const;
